CREATE TABLE IF NOT EXISTS BRANDS (
    BRAND_ID INTEGER NOT NULL,
    NAME VARCHAR(250) NOT NULL,
    PRIMARY KEY (BRAND_ID)
);

CREATE TABLE IF NOT EXISTS PRICES (
    PRICE_ID INTEGER NOT NULL AUTO_INCREMENT,
    BRAND_ID INTEGER NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    PRICE_LIST INTEGER NOT NULL,
    PRODUCT_ID INTEGER NOT NULL,
    PRIORITY TINYINT NOT NULL,
    PRICE NUMERIC NOT NULL,
    CURR VARCHAR(3) NOT NULL,
    PRIMARY KEY (PRICE_ID),
    FOREIGN KEY (BRAND_ID) REFERENCES BRANDS(BRAND_ID)
);
